"""V2 enums and constants."""

from __future__ import annotations


class Role:
    ADMIN = "ADMIN"
    USER = "USER"
    ALL = [ADMIN, USER]


class OperationType:
    ECOM = "ECOM"
    RTL = "RTL"
    WHLS = "WHLS"
    ALL = [ECOM, RTL, WHLS]
    CHANNEL = {
        ECOM: "ECOMMERCE",
        RTL: "RETAIL",
        WHLS: "WHOLESALE",
    }


class UnitStatus:
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    PACKED = "PACKED"
    SHIPPED = "SHIPPED"
    ALL = [AVAILABLE, RESERVED, PACKED, SHIPPED]
    ON_HAND = [AVAILABLE, RESERVED, PACKED]


class OrderStatus:
    UNALLOCATED = "UNALLOCATED"
    PARTIALLY_ALLOCATED = "PARTIALLY_ALLOCATED"
    ALLOCATED = "ALLOCATED"
    PICK_TICKET_READY = "PICK_TICKET_READY"
    PROCESSING = "PROCESSING"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ALL = [
        UNALLOCATED,
        PARTIALLY_ALLOCATED,
        ALLOCATED,
        PICK_TICKET_READY,
        PROCESSING,
        CLOSED,
        CANCELLED,
    ]


class PickTicketStatus:
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ALL = [OPEN, CLOSED, CANCELLED]
    LEGACY_OPEN = frozenset({OPEN, "ACTIVE"})


CLOSED_PICK_TICKET_MESSAGE = (
    "Pick Ticket is closed because the associated order is complete."
)


class AllocationStatus:
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"


class CartonStatus:
    OPEN = "OPEN"
    AWAITING_WEIGHT = "AWAITING_WEIGHT"
    REWEIGH_REQUIRED = "REWEIGH_REQUIRED"
    CLOSED = "CLOSED"


class LedgerType:
    IMPORT = "IMPORT"
    ADJUSTMENT = "ADJUSTMENT"
    RESERVE = "RESERVE"
    UNRESERVE = "UNRESERVE"
    PACK = "PACK"
    UNPACK = "UNPACK"
    SHIP = "SHIP"
    RETURN = "RETURN"
    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"


class ImportType:
    INVENTORY = "INVENTORY"
    ORDERS = "ORDERS"


class ImportBatchStatus:
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ALL = [UPLOADED, VALIDATING, VALIDATED, PROCESSING, COMPLETED, FAILED]
    INVISIBLE = {UPLOADED, VALIDATING, VALIDATED, PROCESSING, FAILED}


APP_VERSION = "2.0.0"
