"""V2 enums and constants."""

from __future__ import annotations


class Role:
    ADMIN = "ADMIN"
    USER = "USER"
    ALL = [ADMIN, USER]


class OperationType:
    ECOM = "ECOM"
    RTL = "RTL"
    WHLS = "WHLS"
    ALL = [ECOM, RTL, WHLS]
    CHANNEL = {
        ECOM: "ECOMMERCE",
        RTL: "RETAIL",
        WHLS: "WHOLESALE",
    }


class UnitStatus:
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    PACKED = "PACKED"
    SHIPPED = "SHIPPED"
    ISSUE_HOLD = "ISSUE_HOLD"
    MISSING = "MISSING"
    DECOMMISSIONED = "DECOMMISSIONED"
    ALL = [AVAILABLE, RESERVED, PACKED, SHIPPED, ISSUE_HOLD, MISSING, DECOMMISSIONED]
    ON_HAND = [AVAILABLE, RESERVED, PACKED]
    NOT_ALLOCATABLE = [RESERVED, PACKED, SHIPPED, ISSUE_HOLD, MISSING, DECOMMISSIONED]


class OrderStatus:
    UNALLOCATED = "UNALLOCATED"
    PARTIALLY_ALLOCATED = "PARTIALLY_ALLOCATED"
    ALLOCATED = "ALLOCATED"
    PICK_TICKET_READY = "PICK_TICKET_READY"
    PROCESSING = "PROCESSING"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ALL = [
        UNALLOCATED,
        PARTIALLY_ALLOCATED,
        ALLOCATED,
        PICK_TICKET_READY,
        PROCESSING,
        PARTIALLY_FULFILLED,
        CLOSED,
        CANCELLED,
    ]
    ALLOCATION_ELIGIBLE = [UNALLOCATED, PARTIALLY_ALLOCATED, PARTIALLY_FULFILLED]


class PickTicketStatus:
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ALL = [OPEN, CLOSED, CANCELLED]
    LEGACY_OPEN = frozenset({OPEN, "ACTIVE"})


CLOSED_PICK_TICKET_MESSAGE = (
    "Pick Ticket is closed because the associated order is complete."
)
CLOSED_PICK_TICKET_UPDATE_MESSAGE = "Pick Ticket is closed and cannot be updated."
REPLACEMENT_UNAVAILABLE_MESSAGE = (
    "Selected replacement unit is no longer available. Select another location."
)


class AllocationStatus:
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    MISSING = "MISSING"
    ALL = [ACTIVE, RELEASED, MISSING]
    LIVE = [ACTIVE]


class CartonStatus:
    OPEN = "OPEN"
    AWAITING_WEIGHT = "AWAITING_WEIGHT"
    REWEIGH_REQUIRED = "REWEIGH_REQUIRED"
    CLOSED = "CLOSED"


class LedgerType:
    IMPORT = "IMPORT"
    ADJUSTMENT = "ADJUSTMENT"
    RESERVE = "RESERVE"
    UNRESERVE = "UNRESERVE"
    PACK = "PACK"
    UNPACK = "UNPACK"
    SHIP = "SHIP"
    RETURN = "RETURN"
    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"
    ISSUE_HOLD = "ISSUE_HOLD"
    ISSUE_RESOLVED = "ISSUE_RESOLVED"
    MISSING_CONFIRMED = "MISSING_CONFIRMED"
    UNIT_DECOMMISSIONED = "UNIT_DECOMMISSIONED"


class InventoryIssueType:
    PICK_UNIT_NOT_FOUND = "PICK_UNIT_NOT_FOUND"
    ALL = [PICK_UNIT_NOT_FOUND]


class InventoryIssueStatus:
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    MISSING = "MISSING"
    TO_DELETE = "TO_DELETE"
    ALL = [OPEN, RESOLVED, MISSING, TO_DELETE]


class ImportType:
    INVENTORY = "INVENTORY"
    ORDERS = "ORDERS"


class ImportBatchStatus:
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ALL = [UPLOADED, VALIDATING, VALIDATED, PROCESSING, COMPLETED, FAILED]
    INVISIBLE = {UPLOADED, VALIDATING, VALIDATED, PROCESSING, FAILED}


class ShippingStatus:
    NOT_READY = "NOT_READY"
    PENDING_TRACKING = "PENDING_TRACKING"
    TRACKING_COMPLETE = "TRACKING_COMPLETE"
    ALL = [NOT_READY, PENDING_TRACKING, TRACKING_COMPLETE]


class ShippingLabelStatus:
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    ALL = [PENDING, VALIDATED]


class TrackingCarrier:
    UPS = "UPS"
    FEDEX = "FEDEX"
    OTHER = "OTHER"
    ALL = [UPS, FEDEX, OTHER]


TRACKING_NUMBER_MAX_LEN = 64
EOD_TIMEZONE = "America/New_York"

APP_VERSION = "2.0.0"
